name: 'Howdy'
description: 'Howdy!'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'Folks'
outputs:
  time:
    description: ' ...what time is it?'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
